(defvar wtconfig-path "C:/Users/Dove/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json")
(defvar wtconfig-buffer (find-file-noselect wtconfig-path t))

(defun dove-set-wt-cursor (type)
    "set cursor for WindowsTerminal"
    (if (and (not (display-graphic-p)) wtconfig-buffer)
		(let ((buffer-cache (current-buffer)))
			(when wtconfig-buffer
				(set-buffer wtconfig-buffer)
				(beginning-of-buffer)
				(search-forward "cursorShape")
				(forward-word)
				(backward-word)
				(let ((word-length (length (thing-at-point 'word))))
					(delete-char word-length)
					(insert type)
				)
				(save-buffer)
				(set-buffer buffer-cache)
			)
		)
	)
)

(defun dsetcursor-bar ()
  (dove-set-wt-cursor "bar"))
(defun dsetcursor-filled-box ()
  (dove-set-wt-cursor "filledBox"))
(defun dsetcursor-underscore ()
  (dove-set-wt-cursor "doubleUnderscore"))

(defun work-on-windows-terminal (&optional path)
  (when (equal nil path)
	(message "path is nil"))
)

(when (not (display-graphic-p))
    (add-hook 'evil-insert-state-entry-hook  'dsetcursor-bar)
    (add-hook 'evil-insert-state-exit-hook   'dsetcursor-filled-box)
    (add-hook 'evil-replace-state-entry-hook 'dsetcursor-underscore)
    (add-hook 'evil-replace-state-exit-hook  'dsetcursor-filled-box)
)

(provide 'dove-windows-terminal)
